### ISSUE TITLE
1주차 진행

### ISSUE THREAD

**Issue by ccf05017** [CodeSoom/project-react-1-ccf05017#1]
1. 이 앱을 언제 사용하나요?
- 특별한 기념일에 Yen토퍼에서 판매중인 케이크 토퍼를 확인하고, 구매하기 위해 사용합니다.

2. 제약 조건은 무엇인가요?
- 카테고리 별로 정리된 케이크 토퍼 목록을 볼 수 있어야 합니다.
- 케이크 토퍼 상세 목록에서 사진을 여러개 볼 수 있어야 합니다.
- 케이크 토퍼 상세 목록에서 구매할 수량을 선택하고 주문할 수 있어야 합니다.
- 주문 시 배송지 정보를 입력해야 합니다.
- 결제는 계좌이체로만 가능합니다.
    - 계좌이체를 진행 할 계좌 번호를 볼 수 있어야 합니다. 
- 회원가입이 없습니다.
    - 매 주문마다 배송지 정보를 입력해야 합니다.

3. 구체적인 사례는 무엇인가요?
- 사용자가 접속해서 원하는 카테고리에 마우스를 갖다 뎁니다.
- 판매중인 케이크 토퍼 목록을 확인합니다.
- 구매하고자 하는 케이크 토퍼를 선택합니다.
- 해당 케이크 토퍼의 상세 사진을 확인합니다.
- 구매하고자 하는 수량을 입력합니다.
- 해당 제품을 주문합니다.
- 주문한 제품을 받을 배송지를 입력합니다.
- 상품 가격을 지불할 계좌이체 번호를 확인합니다.

4. 이번주에 구현 할 기능을 우선 순위대로 작성해주세요.
- [x] 인수 테스트를 위한 Mock API 서버 구축(json-server)
- [x] 메인 페이지 구현
    - [x] 카테고리 목록 렌더링
    - [x] 카테고리 별 마우스 호버링 시 해당 카테고리에 해당하는 케이크 토퍼 목록 렌더링
    - [x] 케이크 토퍼 목록해서 상품 클릭 시 상세 페이지로 이동
- [x] 상세 페이지 구현
    - [x] 케이크 토퍼의 상세 정보 렌더링
    - [x] 주문서 폼(구매자명, 구매자 휴대폰 번호, 배송받을 주소, 수량) 기능 구현
- [x] 주문하기 기능 구현
    - [x] 사용자가 작성한 주문 정보를 상점 주인에게 전달
        - 후보군: 텔레그램, 카카오톡, 메일
        - [x] 텔레그램 메시지 전송 봇 구성
    - [x] 주문이 성공하면 입금할 계좌를 보여준다.

**Comment by hannut91** [comment]
이번주에는 사람들이 케이크 목록과 케이크 상세 페이지에서 케이크의 상세 정보를 볼 수 있겠군요!

**Comment by ccf05017** [comment]
중요한 건 아니지만 케이크가 아니라 케이크 토퍼 판매 페이지입니다 ㅎㅎㅎㅎㅎ
믿기지 않으시겠지만 케이크가 아니라 케이크에 꽂는 '종이 쪼가리'가 메인인 쇼핑몰 프로젝트에요! ㅋㅋㅋㅋ

생각보다(?) 굉장히 의외로 사용하시는 분들이 꾀 있더라구요 ㅎㅎ

**Comment by wholemann** [comment]
만약에 진행하시다가 상세 페이지 구현까지 시간이 녹록치 않다면

근데 당장 이번주에 비지니스를 개시하고 싶다면?

저는 상세 페이지 구현은 notion으로 대체하겠습니다ㅋㅋㅋ

무조건 이번주에 공개하는 걸로 해주세요. 자랑해주세요 범진님!

**Comment by ccf05017** [comment]
수형님 조언대로 이번주에 서비스를 즉시 개시한다면 주문 받는 것까지 필요할 것 같아서 주문하기 기능을 요구사항에 추가했습니다 ㅎㅎ
일단 아무튼 구매하려는 사람이 어디로 뭘 받을지만 받을 수 있게 만드는 걸 목표로 잡았습니다.
이번주에 완성하게 되면
- 사용자가 카테고리 별로 상품 목록을 볼 수 있다.
- 사용자가 상품 상세 정보 화면에서 주문할 수 있다.
- 요청된 주문이 점주에게 전달된다. (어떤 형태로건 아무튼 전달된다.)
